# Routes globales (sans tenant)
controllers:
    resource:
        path: ../src/Controller/App/
        namespace: App\Controller\App
    type: attribute

# Routes tenant (avec pr√©fixe /{tenantKey})
tenant_routes:
    resource: routes/tenant.yaml
