doctrine_migrations:
    em: main
    migrations_paths:
        "DoctrineMigrations": "%kernel.project_dir%/migrations"
    enable_profiler: false
    all_or_nothing: true
    transactional: true
    check_database_platform: true
