doctrine:
    dbal:
        default_connection: tenant

        connections:
            main:
                url: "%env(resolve:DATABASE_URL_MAIN)%"

            tenant:
                wrapper_class: App\Tenant\TenantConnectionWrapper
                url: "%env(resolve:DATABASE_URL_TENANT_BASE)%"
