doctrine:
    dbal:
        default_connection: main

        connections:
            main:
                url: "%env(resolve:DATABASE_URL_MAIN)%"

            tenant:
                url: "%env(resolve:DATABASE_URL_TENANT)%"

    orm:
        default_entity_manager: main

        entity_managers:
            main:
                connection: main
                mappings:
                    Main:
                        is_bundle: false
                        type: attribute
                        dir: "%kernel.project_dir%/src/Entity/Main"
                        prefix: 'App\Entity\Main'

                    Portal:
                        is_bundle: false
                        type: attribute
                        dir: "%kernel.project_dir%/src/Entity/Portal"
                        prefix: 'App\Entity\Portal'

            tenant:
                connection: tenant
                mappings:
                    Tenant:
                        is_bundle: false
                        type: attribute
                        dir: "%kernel.project_dir%/src/Entity/Tenant"
                        prefix: 'App\Entity\Tenant'
