doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: "%env(resolve:DATABASE_URL)%"

            tenant:
                # Valeurs placeholder, remplac√©es dynamiquement par Hakam
                driver: "pdo_pgsql"
                host: ""
                port: ""
                dbname: ""
                user: ""
                password: ""

    orm:
        default_entity_manager: default

        entity_managers:
            default:
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        type: attribute
                        dir: "%kernel.project_dir%/src/Entity/Main"
                        prefix: 'App\Entity\Main'

            tenant:
                connection: tenant
                mappings:
                    Tenant:
                        is_bundle: false
                        type: attribute
                        dir: "%kernel.project_dir%/src/Entity/Tenant"
                        prefix: 'App\Entity\Tenant'
