hakam_multi_tenancy:
    tenant_entity_manager:
        name: tenant
        connection: tenant
        mapping:
            type: attribute
            dir: "%kernel.project_dir%/src/Entity/Tenant"
            prefix: "App\\Entity\\Tenant"
            is_bundle: false

    tenant_connection:
        name: tenant
        connection: tenant

    tenant_database_className: App\Entity\Main\TenantDbConfig
    tenant_database_identifier: databaseName
    tenant_config_provider: App\Tenant\TenantConfigProvider

    tenant_migration:
        enabled: true
        path: "%kernel.project_dir%/migrations/tenant"
