security:
    password_hashers:
        App\Entity\Portal\PortalUser:
            algorithm: auto

    providers:
        portal_user_provider:
            entity:
                class: App\Entity\Portal\PortalUser
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: portal_user_provider
            entry_point: App\Security\PortalLoginAuthenticator

            form_login:
                login_path: portal_login
                check_path: portal_login

            logout:
                path: portal_logout
                target: portal_login
            custom_authenticator: App\Security\PortalLoginAuthenticator

            remember_me:
                secret: "%kernel.secret%"
                lifetime: 604800
                path: /
                # by default, the feature is enabled by checking a checkbox in the
                # login form, uncomment the following line to always enable it.
                #always_remember_me: true

    access_control:
        - { path: ^/portal/login, roles: PUBLIC_ACCESS }
        - { path: ^/portal, roles: ROLE_TENANT }

when@test:
    security:
        password_hashers:
            App\Entity\Portal\PortalUser:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
